import { createReadStream, type ReadStream } from 'node:fs';
import { mkdir, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import type { Env } from '../config/env';
import { StorageService } from './storage.service';

/**
 * Files on the machine's own disk.
 *
 * What a single server wants, and what the test suite uses. Not what a platform
 * with an ephemeral filesystem wants — see `S3StorageService` and the note on
 * `StorageService`.
 */
@Injectable()
export class LocalStorageService extends StorageService {
  private readonly logger = new Logger(LocalStorageService.name);
  private readonly root: string;

  constructor(config: ConfigService<Env, true>) {
    super();
    this.root = resolve(config.get('UPLOADS_DIR', { infer: true }));
  }

  async save(key: string, contents: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents);
  }

  read(key: string): ReadStream {
    return createReadStream(this.pathFor(key));
  }

  async remove(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch (cause) {
      this.logger.warn(
        `Could not delete ${key}: ${cause instanceof Error ? cause.message : String(cause)}`,
      );
    }
  }

  /**
   * Resolves a key inside the storage root, and refuses anything that escapes
   * it — a key is generated by `keyFor`, but this is the one place where a value
   * that came from outside could turn into a path.
   */
  private pathFor(key: string): string {
    const path = resolve(join(this.root, key));

    if (path !== this.root && !path.startsWith(this.root + sep)) {
      throw new Error(`Refusing a storage key that escapes the root: ${key}`);
    }

    return path;
  }
}
